# Generated by Django 3.0.4 on 2020-03-29 10:35

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('champ', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('description', models.TextField(max_length=1000)),
                ('location', models.TextField(max_length=1000)),
                ('isfinished', models.BooleanField()),
                ('url', models.URLField(max_length=1000)),
                ('compdates', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Phases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=200)),
                ('evkey', models.CharField(max_length=100)),
                ('phase_type', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RawData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_data', django_mysql.models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('player_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='player', to='players.Player')),
            ],
        ),
        migrations.CreateModel(
            name='MatchRawData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=1000)),
                ('json_data', django_mysql.models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comp', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='competition', to='tabletennis.Competition')),
            ],
        ),
        migrations.AddField(
            model_name='competition',
            name='raw_comp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='competition_rawdata', to='tabletennis.RawData'),
        ),
    ]
