# Generated by Django 3.0.4 on 2020-03-12 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tabletennis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='away',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away', to='tabletennis.Player'),
        ),
        migrations.AlterField(
            model_name='match',
            name='home',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home', to='tabletennis.Player'),
        ),
        migrations.AlterField(
            model_name='match',
            name='team_away',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teams_away', to='tabletennis.Team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='team_home',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teams_home', to='tabletennis.Team'),
        ),
    ]
