# Generated by Django 3.0.3 on 2020-03-18 20:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tabletennis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deletedfixture',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deletedfixture',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
