# Generated by Django 3.0.4 on 2020-05-05 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tabletennis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchScrapingError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error', models.TextField()),
                ('desc', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('champ', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ChampError', to='tabletennis.TTCompetition')),
            ],
        ),
    ]
