# Generated by Django 3.0.4 on 2020-03-24 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabletennis', '0002_auto_20200318_2026'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchIssue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('champ', models.CharField(max_length=200)),
                ('phase', models.CharField(max_length=300)),
                ('url', models.URLField()),
                ('home', models.TextField(max_length=1000)),
                ('away', models.TextField(max_length=1000)),
                ('Desc', models.CharField(max_length=200)),
                ('match', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('error', models.TextField(max_length=1000)),
            ],
        ),
    ]
