# Generated by Django 3.0.4 on 2020-03-13 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabletennis', '0002_auto_20200312_2212'),
    ]

    operations = [
        migrations.CreateModel(
            name='Missingdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home', models.CharField(max_length=300)),
                ('away', models.CharField(max_length=300)),
                ('url', models.URLField(max_length=300)),
                ('phase', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
