# Generated by Django 3.0.3 on 2020-02-21 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=1000)),
                ('desc', models.CharField(max_length=1000)),
                ('time', models.CharField(max_length=1000)),
                ('loc', models.CharField(max_length=1000)),
                ('locdesc', models.CharField(max_length=1000)),
                ('venue', models.CharField(max_length=1000)),
                ('rtime', models.CharField(max_length=1000)),
                ('status', models.CharField(max_length=1000)),
                ('isteam', models.CharField(max_length=1000)),
                ('hascomps', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urlfortournement', models.URLField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='TournamentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('champ', models.CharField(max_length=1000)),
                ('status', models.CharField(max_length=1000)),
                ('dates', models.CharField(max_length=1000)),
                ('datesdesc', models.CharField(max_length=1000)),
                ('champdesc', models.CharField(max_length=1000)),
                ('location', models.CharField(max_length=1000)),
                ('events', models.CharField(max_length=1000)),
                ('phases', models.CharField(max_length=1000)),
                ('locations', models.CharField(max_length=1000)),
                ('isfinished', models.BooleanField()),
                ('urltournement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urlfortour', to='scrape.Tournament')),
            ],
        ),
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home', models.CharField(max_length=1000)),
                ('away', models.CharField(max_length=1000)),
                ('hasstats', models.CharField(max_length=1000)),
                ('team_a', models.CharField(blank=True, max_length=1000, null=True)),
                ('team_b', models.CharField(blank=True, max_length=1000, null=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match', to='scrape.Matches')),
            ],
        ),
        migrations.AddField(
            model_name='matches',
            name='champ',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='champinfo', to='scrape.TournamentInfo'),
        ),
    ]
