# Generated by Django 3.0.3 on 2020-02-19 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ittf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournment_name', models.CharField(max_length=500)),
                ('tournment_location', models.CharField(max_length=500)),
                ('tournment_desc', models.CharField(max_length=500)),
                ('isfinished', models.BooleanField()),
                ('match_desc', models.CharField(max_length=500)),
                ('match_time', models.DateTimeField()),
                ('isteam', models.BooleanField(max_length=500)),
                ('home', models.CharField(max_length=500)),
                ('away', models.CharField(max_length=500)),
                ('teamA', models.CharField(default=None, max_length=500)),
                ('team2', models.CharField(default=None, max_length=500)),
            ],
        ),
    ]
